#Use for AOT testing, replace port with a proper container port
spring.docker.compose.enabled=false

spring.datasource.url=jdbc:postgresql://127.0.0.1:64047/jdbcdb
spring.datasource.username=demo
spring.datasource.password=demo